package com.fitbit.mysqlloganalyzer;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Map;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ivanbahdanau' at '4/8/15 10:16 AM' with Gradle 2.1
 *
 * @author ivanbahdanau, @date 4/8/15 10:16 AM
 */
public class Analyzer {


    public static void main(String[] args) throws IOException {
        String filePath = args[0];
        MysqlSlowLogDataReader mysqlSlowLogDataReader = new MysqlSlowLogDataReader();
        final Map<String, List<MysqlSlowLogObject.MysqlLogRecord>> processedData = mysqlSlowLogDataReader.readFile(new File(filePath));
        new TotalTimeSpentSlowSqlPrinter(processedData).printSorted();
        new QueryPayloadPrinter(processedData).printSorted();
    }

}
