package com.fitbit.mysqlloganalyzer;

import java.io.File;
import java.io.IOException;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ivanbahdanau' at '4/8/15 10:16 AM' with Gradle 2.1
 *
 * @author ivanbahdanau, @date 4/8/15 10:16 AM
 */
public class Analyzer {


    public static void main(String[] args) throws IOException {
        String filePath = args[0];
        MysqlSlowLogDataReader mysqlSlowLogDataReader = new MysqlSlowLogDataReader();
        List<MysqlSlowLogObject.MysqlLogRecord> processedData = mysqlSlowLogDataReader.readFile(new File(filePath));
        Collections.sort(processedData, new Comparator<MysqlSlowLogObject.MysqlLogRecord>() {
            @Override
            public int compare(MysqlSlowLogObject.MysqlLogRecord o1, MysqlSlowLogObject.MysqlLogRecord o2) {
                return Float.valueOf(o2.getQueryTime()).compareTo(o1.getQueryTime());
            }
        });

        print(processedData);
    }

    private static void print(List<MysqlSlowLogObject.MysqlLogRecord> processedData) {
        int counter = 0;
        for (MysqlSlowLogObject.MysqlLogRecord mysqlLogRecord : processedData) {
            System.out.println(mysqlLogRecord.getQueryTime() + ": " + mysqlLogRecord.getSqlQuery());
            if (counter++ > 100) {
                return;
            }
        }
    }
}
