package com.fitbit.mysqlloganalyzer;

import com.fitbit.mysqlloganalyzer.Analyzer;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ivanbahdanau' at '4/8/15 10:16 AM' with Gradle 2.1
 *
 * @author ivanbahdanau, @date 4/8/15 10:16 AM
 */
public class AnalyzerTest {
    @Test public void testSomeLibraryMethod() {
        Analyzer classUnderTest = new Analyzer();

    }
}
